config-version = 2

after-startup-command = []
start-at-login = false
auto-reload-config = false

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B",
                         "C", "D", "E", "F", "G", "I", "M", "N", "O", "P", "Q",
                         "R", "T", "U", "V", "W", "X", "Y", "Z"]

on-mode-changed = []
focus-follows-mouse.enabled = false
key-mapping.preset = 'qwerty'

gaps.inner.horizontal = 0
gaps.inner.vertical = 0
gaps.outer.left = 0
gaps.outer.bottom = 0
gaps.outer.top = 0
gaps.outer.right = 0

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    ctrl-1 = 'workspace 1'
    ctrl-2 = 'workspace 2'
    ctrl-3 = 'workspace 3'
    ctrl-4 = 'workspace 4'
    ctrl-5 = 'workspace 5'
    ctrl-6 = 'workspace 6'
    ctrl-7 = 'workspace 7'
    ctrl-8 = 'workspace 8'
    ctrl-9 = 'workspace 9'
    ctrl-a = 'workspace A'
    ctrl-b = 'workspace B'
    ctrl-c = 'workspace C'
    ctrl-d = 'workspace D'
    ctrl-e = 'workspace E'
    ctrl-f = 'workspace F'
    ctrl-g = 'workspace G'
    ctrl-i = 'workspace I'
    ctrl-m = 'workspace M'
    ctrl-n = 'workspace N'
    ctrl-o = 'workspace O'
    ctrl-p = 'workspace P'
    ctrl-q = 'workspace Q'
    ctrl-r = 'workspace R'
    ctrl-t = 'workspace T'
    ctrl-u = 'workspace U'
    ctrl-v = 'workspace V'
    ctrl-w = 'workspace W'
    ctrl-x = 'workspace X'
    ctrl-y = 'workspace Y'
    ctrl-z = 'workspace Z'

    ctrl-shift-1 = 'move-node-to-workspace 1'
    ctrl-shift-2 = 'move-node-to-workspace 2'
    ctrl-shift-3 = 'move-node-to-workspace 3'
    ctrl-shift-4 = 'move-node-to-workspace 4'
    ctrl-shift-5 = 'move-node-to-workspace 5'
    ctrl-shift-6 = 'move-node-to-workspace 6'
    ctrl-shift-7 = 'move-node-to-workspace 7'
    ctrl-shift-8 = 'move-node-to-workspace 8'
    ctrl-shift-9 = 'move-node-to-workspace 9'
    ctrl-shift-a = 'move-node-to-workspace A'
    ctrl-shift-b = 'move-node-to-workspace B'
    ctrl-shift-c = 'move-node-to-workspace C'
    ctrl-shift-d = 'move-node-to-workspace D'
    ctrl-shift-e = 'move-node-to-workspace E'
    ctrl-shift-f = 'move-node-to-workspace F'
    ctrl-shift-g = 'move-node-to-workspace G'
    ctrl-shift-i = 'move-node-to-workspace I'
    ctrl-shift-m = 'move-node-to-workspace M'
    ctrl-shift-n = 'move-node-to-workspace N'
    ctrl-shift-o = 'move-node-to-workspace O'
    ctrl-shift-p = 'move-node-to-workspace P'
    ctrl-shift-q = 'move-node-to-workspace Q'
    ctrl-shift-r = 'move-node-to-workspace R'
    ctrl-shift-t = 'move-node-to-workspace T'
    ctrl-shift-u = 'move-node-to-workspace U'
    ctrl-shift-v = 'move-node-to-workspace V'
    ctrl-shift-w = 'move-node-to-workspace W'
    ctrl-shift-x = 'move-node-to-workspace X'
    ctrl-shift-y = 'move-node-to-workspace Y'
    ctrl-shift-z = 'move-node-to-workspace Z'

    ctrl-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
